language: csharp
solution: DataCommand.Net.sln
mono: none
dotnet: 1.0.0-preview3-004056
script:
  - xbuild /p:Configuration=Release DataCommand.Net.sln
  - dotnet test ./test/DataCommand.Core.Tests/project.json
