language: csharp
sudo: required
dist: trusty
solution: DataCommand.Net.sln
mono: none
dotnet: 1.0.1
script:
  - dotnet restore
  - dotnet build
  - dotnet test ./test/DataCommand.Core.Tests/DataCommand.Core.Tests.csproj

  deploy:
    provider: script
    skip_cleanup: true
    script:
        - dotnet pack
        - nuget push ./src/DataCommand.Core/**.nupkg $NUGET_API_KEY -verbosity detailed
    on:
        branch: master