language: csharp
sudo: required
dist: trusty
solution: DataCommand.Net.sln
mono: none
dotnet: 1.0.0-preview2-003131
script:
  - dotnet restore
  - dotnet build
  - dotnet test ./test/DataCommand.Core.Tests/DataCommand.Core.Tests.csproj